Name: `Elina Hozhabri`

<div dir='rtl'>
سوال اول: معکوس کردن رشته
</div>

In [32]:
def reverse_string():
    str = input("Enter your string:")
    print(f"Your string is {str}")
    print(f"Its reverse is : {str[::-1]}")

if __name__ == "__main__":
    reverse_string()

Your string is hello
Its reverse is : olleh


<div dir='rtl'>
سوال دوم: عدد پرتکرار
</div>

In [33]:
from statistics import mode

def mostNumber():
    nums = input("Enter your array (split by space): ")
    arr = list(map(int, nums.split()))
    print(f"Your array is {arr}")
    print(f"Most frequet number is : {mode(arr)}")

if __name__ == "__main__":
    mostNumber()
    

Your array is [1, 2, 2, 3, 3, 3, 4]
Most frequet number is : 3


<div dir='rtl'>
سوال سوم: بررسی عدد اول
</div>

In [34]:
from math import sqrt

def checkPrime(num):
    if num <= 1:
        return False
    elif num == 2:
        return True
    for i in range(3, int(sqrt(num)) + 1):
        if num % i == 0:
            print(f'{i} ')
            return False
    return True

def isPrime():
    num = int(input("Enter your number: "))
    print(f"Your number is {num}")
    prime = checkPrime(num)
    if prime == True:
        print(f'{num} is prime')
    else:
        print(f'{num} is NOT prime')

if __name__ == "__main__":
    isPrime()

Your number is 7
7 is prime


<div dir='rtl'>
سوال چهارم: جمع قطر اصلی ماتریس
</div>

In [36]:
import numpy as np

def sumOfTrace():
    size = int(input("Enter size of matrix: "))
    matrix = []
    print(f'Enter your matrix of size {size*size}:')
    while len(matrix)<size*size:
        matrix_str = input()
        if not matrix_str.strip():
            continue
        matrix.extend(list(map(int, matrix_str.split(' '))))
    matrix = np.array(matrix).reshape(size,size)
    print(f'Your matrix is:\n {matrix}')
    sum = np.trace(matrix)
    print(f'Sum of the main diameters of the matrix is: {sum}')

if __name__ == "__main__":
    sumOfTrace()


Enter your matrix of size 9:
Your matrix is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the main diameters of the matrix is: 15


<div dir='rtl'>
سوال پنجم: مرتب‌سازی کلمات در یک جمله
</div>

In [37]:
def sortWords():
    str = input("Enter your string:")
    words = sorted(str.split(' '))
    sorted_str = ' '.join(words)
    print(f'your string is: {str}')
    print(f'Sorted: {sorted_str}')

if __name__ == "__main__":
    sortWords()

your string is: machine learning is fun
Sorted: fun is learning machine


<div dir='rtl'>
سوال اختیاری اول: </div>

In [1]:
import pandas as pd

def createCSV():
    data = {
        "Product": [
            "shampo", "rice", "oil", "pasta", "yogurt", "milk", "coca cola", "ice cream", "tea"
        ],
        "Price": [
            990000, 3000000, 1500000, 1800000, 1000000, 470000, 300000, 200000, 2000000

        ],
        "Date": [
            "1404/5/3", "1404/6/10", "1404/6/10", "1404/5/14", "1404/5/3", "1404/5/3", "1404/5/14", "1404/6/10", "1404/5/10"
        ]
    }

    df = pd.DataFrame(data)
    df.to_csv("Products.csv", index=False)
    print("File created sucessfully.")

def csvFile():
    df = pd.read_csv("Products.csv")
    df.head(10)
    print(f'Total sales: {df["Price"].sum()} ريال')
    print(f'Average sales: {df["Price"].mean():.2f} ريال')
    sale_by_day = df.groupby("Date")["Price"].sum()
    print(f'Max sale in one day: {sale_by_day.max()} ريال in date {sale_by_day.idxmax()}')

if __name__ == "__main__":
    createCSV()
    csvFile()

File created sucessfully.
Total sales: 11260000 ريال
Average sales: 1251111.11 ريال
Max sale in one day: 4700000 ريال in date 1404/6/10


<div dir='rtl'>
سوال اختیاری دوم: لینک <a href="https://github.com/ElinaH83/Questions-for-interview">GitHub</a>
</div>